[project]
name = "helmkit"
version = "0.7.7"
description = "Parse HELM strings into RDKit molecules"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "rdkit>=2025.3.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "dead>=2.1.0",
    "polars>=1.31.0",
    "prek>=0.3.1",
    "pypept",
    "pytest>=8.4.1",
    "pyupgrade>=3.20.0",
    "reorder-python-imports>=3.15.0",
    "tqdm>=4.67.1",
]

[tool.uv.sources]
pypept = { git = "https://github.com/Boehringer-Ingelheim/pyPept.git" }

[tool.hatch.build]
exclude = [
    ".github",
    ".gitignore",
    ".pre-commit-config.yaml",
    "benchmarks",
    "dev",
    "tests",
]

[tool.ruff]
# Enable preview features.
preview = true

[tool.ruff.lint]
ignore = ["I001", "N999"]

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.ty.rules]
all = "error"
unsound-return-statement = "ignore"

[tool.ty.src]
include = ["src"]
exclude = ["tests"]

[tool.pyrefly]
project-includes = ["src/**/*.py"]
